CREATE TABLE W1_LINK(
	RES_ID VARCHAR(25) NOT NULL,
	TITLE TEXT,
	LINKURL TEXT,
	CONTENT TEXT,
	DISP_DATE DATETIME,
	VIEW_ORDER INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
