CREATE TABLE N4_2TICKER(
	RES_ID VARCHAR(25) NOT NULL,
	COMMENT TINYTEXT,
	LINKURL TEXT,
	DISP_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
