CREATE TABLE APP_ID_PASS(
	RES_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	BO_ID TINYTEXT,
	BO_PW TINYTEXT,
	PERMIT_IP_LST TEXT,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
INSERT INTO APP_ID_PASS(BO_ID,BO_PW,PERMIT_IP_LST)VALUES('zeeksdg','pass','210.138.173.44,114.174.230.240');
INSERT INTO APP_ID_PASS(BO_ID,BO_PW,PERMIT_IP_LST)VALUES('other','pass','free');

CREATE TABLE APP_INIT_DATA(
	RES_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	EMAIL1 TINYTEXT,
	EMAIL2 TINYTEXT,
	CONTENT TEXT,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);

/* TEST INSERT */
INSERT INTO APP_INIT_DATA(EMAIL1,EMAIL2,CONTENT)VALUES('info@all-internet.jp','info@all-internet.jp','');

CREATE TABLE N3_2WHATSNEW(
	RES_ID VARCHAR(25) NOT NULL,
	TITLE TEXT,
	CONTENT TEXT,
	LINK TEXT,
	DISP_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	LINK_FLG CHAR(1) DEFAULT 1,
	IMG_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);

CREATE TABLE N3_2WHATSNEW_PAGE(
	RES_ID INT,
	PAGE_FLG INT DEFAULT 0
);
INSERT INTO N3_2WHATSNEW_PAGE(RES_ID,PAGE_FLG)VALUES('1','0');

CREATE TABLE S7_CATEGORY_MST(
	CATEGORY_CODE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME TEXT,
	CATEGORY_DETAILS TEXT,
	VIEW_ORDER INT UNSIGNED,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	DEL_FLG CHAR(1) DEFAULT 0
);

CREATE TABLE S7_2_PRODUCT_LST(
	RES_ID VARCHAR(25) NOT NULL,
	CATEGORY_CODE INT UNSIGNED,
	TITLE TEXT,
	CONTENT TEXT,
	DETAIL_CONTENT TEXT,
	TITLE_TAG TEXT,
	YOUTUBE TEXT,
	IMG_FLG CHAR(1) DEFAULT 1,
	DISP_DATE DATETIME,
	VIEW_ORDER INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
