CREATE TABLE COLUMN_CATEGORY_MST(
  CATEGORY_CODE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME TEXT,
  VIEW_ORDER INT UNSIGNED,
  INS_DATE DATETIME,
  UPD_DATE DATETIME,
  DISPLAY_FLG CHAR(1) DEFAULT 1,
  DEL_FLG CHAR(1) DEFAULT 0
);

CREATE TABLE COLUMN_PRODUCT_LST(
  RES_ID VARCHAR(25) NOT NULL,
  CATEGORY_CODE INT UNSIGNED,
  TITLE TEXT,
  CONTENT1 TEXT,
  IMG_FLG CHAR(1) DEFAULT 1,
  DISP_DATE DATETIME,
  DISPLAY_FLG CHAR(1) DEFAULT 1,
  UPD_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  DEL_FLG CHAR(1) DEFAULT 0,
  PRIMARY KEY(RES_ID)
);
