-- カテゴリ --
CREATE TABLE S7_3_CATEGORY_MST(
	CATEGORY_CODE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME TEXT,
	CATEGORY_DETAILS TEXT,
	RES_ID VARCHAR(25) NOT NULL,
	VIEW_ORDER INT UNSIGNED,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	DEL_FLG CHAR(1) DEFAULT 0
);

CREATE TABLE S7_3_PRODUCT_LST(
	RES_ID VARCHAR(25) NOT NULL,
	CATEGORY_CODE TEXT,
	TITLE TEXT,
	CONTENT TEXT,
	DETAIL_CONTENT TEXT,
	TITLE_TAG TEXT,
	YOUTUBE TEXT,
	IMG_FLG CHAR(1) DEFAULT 1,
	DISP_DATE DATETIME,
	VIEW_ORDER INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);

CREATE TABLE S7_3_VIEW_ORDER_LIST (
  C_ID varchar(25) default '',
  RES_ID varchar(25) NOT NULL default '',
  VIEW_ORDER int(10) unsigned default NULL
);

CREATE TABLE S7_3_VIEW_ORDER_LIST2 (
  C_ID varchar(25) default '',
  RES_ID varchar(25) NOT NULL default '',
  VIEW_ORDER int(10) unsigned default NULL
);
