
CREATE TABLE W3_S1_PRODUCT_LST(
	RES_ID VARCHAR(25) NOT NULL,
	TITLE TEXT,
	CONTENT TEXT,
	DISP_DATE DATETIME,
	VIEW_ORDER INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,

	TYPE TINYTEXT,
	SIZE INT UNSIGNED,
	EXTENTION TEXT,
	PDF_FLG CHAR(1) DEFAULT 0,

	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
