
CREATE TABLE APP_INIT_DATA(
	RES_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	EMAIL1 TINYTEXT,
	EMAIL2 TINYTEXT,
	POP3 TINYTEXT,
	USER_NAME TINYTEXT,
	PASS VARCHAR(25),
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);

/* TEST INSERT */

INSERT INTO APP_INIT_DATA(EMAIL1,EMAIL2,POP3,USER_NAME,PASS)VALUES('syame01@samplepg.zeeksdg.net','syame01@samplepg.zeeksdg.net','mail.samplepg.zeeksdg.net','syame01@samplepg.zeeksdg.net','zeekdemo');

/* DIARY LIST PHP */
CREATE TABLE N6_1DIARY(
	DIARY_ID VARCHAR(25) NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
	SUBJECT TINYTEXT,
	COMMENT TEXT,
	ATTACH_FILE_NAME VARCHAR(128) NOT NULL,
	DISPLAY_FLG CHAR(1) DEFAULT '1',
	REG_DATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	DEL_FLG CHAR(1) NOT NULL DEFAULT '0',
	PRIMARY KEY(DIARY_ID)
);

/* NG WORDS */
CREATE TABLE NG_WORDS(
	KEY_ID CHAR(4) NOT NULL,
	WORDS TEXT,
	UPD_DATE DATETIME
);
INSERT INTO NG_WORDS(KEY_ID,WORDS,UPD_DATE)VALUES('9999','','2005-04-22 16:59:59');
