-- カテゴリ --
CREATE TABLE N3_S7_CATEGORY_MST(
	CATEGORY_CODE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME TEXT,
	CATEGORY_DETAILS TEXT,
	VIEW_ORDER INT UNSIGNED,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	DEL_FLG CHAR(1) DEFAULT 0
);

CREATE TABLE N3_S7_WHATSNEW(
	RES_ID VARCHAR(25) NOT NULL,
	CATEGORY_CODE INT UNSIGNED,
	TITLE TEXT,
	CONTENT TEXT,
	IMG_FLG CHAR(1) DEFAULT 1,
	LINK TEXT,
	LINK_FLG CHAR(1) DEFAULT 1,
	DISP_DATE DATETIME,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);

CREATE TABLE N3_S7_WHATSNEW_PAGE(
	RES_ID INT,
	PAGE_FLG INT DEFAULT 0
);
INSERT INTO N3_S7_WHATSNEW_PAGE(RES_ID,PAGE_FLG)VALUES('1','0');
