-- 管理者情報テーブル作成SQL --
CREATE TABLE CONFIG_MST(
	CONFIG_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME TINYTEXT,
	EMAIL TINYTEXT,
	EMAIL2 TINYTEXT,
	CONTENT TEXT,
	COMPANY_INFO TEXT,
	BANK_INFO TEXT,
	SHOPPING_TITLE TINYTEXT,
	BO_TITLE TINYTEXT,
	BO_ID TINYTEXT,
	BO_PW TINYTEXT,
	PERMIT_IP_LST TEXT,
	UPD_DATE DATETIME,
	DEL_FLG CHAR(1) DEFAULT 0
);

INSERT INTO CONFIG_MST (CONFIG_ID,NAME,EMAIL,EMAIL2,COMPANY_INFO,BANK_INFO,SHOPPING_TITLE,BO_TITLE,BO_ID,BO_PW,UPD_DATE,DEL_FLG,PERMIT_IP_LST) VALUES(1,'','','','','','','','','pass','','0','free');
INSERT INTO CONFIG_MST (CONFIG_ID,NAME,EMAIL,EMAIL2,COMPANY_INFO,BANK_INFO,SHOPPING_TITLE,BO_TITLE,BO_ID,BO_PW,UPD_DATE,DEL_FLG,PERMIT_IP_LST) VALUES(2,'','','','','','','','zeeksdg','pass','','0','210.138.173.44,114.173.123.220,180.17.25.205,118.151.96.205,180.10.246.236,180.26.4.229,61.119.173.50,110.2.115.221,14.161.0.18,118.69.226.204,113.161.70.50,118.69.35.102,115.79.192.120,118.69.34.206');
-- フォーバル案件の場合こちらのＩＤ，ＰＷを追加 --
INSERT INTO CONFIG_MST (CONFIG_ID,NAME,EMAIL,EMAIL2,COMPANY_INFO,BANK_INFO,SHOPPING_TITLE,BO_TITLE,BO_ID,BO_PW,UPD_DATE,DEL_FLG,PERMIT_IP_LST) VALUES(3,'','','','','','','','fvl','pass','','0','free');

-- 顧客情報情報テーブル作成SQL --
CREATE TABLE CUSTOMER_LST(
	CUSTOMER_ID VARCHAR(25) NOT NULL PRIMARY KEY,
	LAST_NAME TINYTEXT,
	FIRST_NAME TINYTEXT,
	LAST_KANA TINYTEXT,
	FIRST_KANA TINYTEXT,
	ALPWD TINYTEXT,
	ZIP_CD1 VARCHAR(3),
	ZIP_CD2 VARCHAR(4),
	STATE VARCHAR(2),
	ADDRESS1 TINYTEXT,
	ADDRESS2 TINYTEXT,
	EMAIL TINYTEXT,
	TEL1 VARCHAR(5),
	TEL2 VARCHAR(5),
	TEL3 VARCHAR(5),
	EXISTING_CUSTOMER_FLG CHAR(1) DEFAULT 0,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DEL_FLG CHAR(1) DEFAULT 0
);

-- 顧客情報情報テーブル作成SQL(クレカ決済前の一時情報保存用) --
CREATE TABLE PRE_CUSTOMER_LST(
	CUSTOMER_ID VARCHAR(25) NOT NULL PRIMARY KEY,
	ORDER_ID VARCHAR(25) NOT NULL,
	LAST_NAME TINYTEXT,
	FIRST_NAME TINYTEXT,
	LAST_KANA TINYTEXT,
	FIRST_KANA TINYTEXT,
	ALPWD TINYTEXT,
	ZIP_CD1 VARCHAR(3),
	ZIP_CD2 VARCHAR(4),
	STATE VARCHAR(2),
	ADDRESS1 TINYTEXT,
	ADDRESS2 TINYTEXT,
	EMAIL TINYTEXT,
	TEL1 VARCHAR(5),
	TEL2 VARCHAR(5),
	TEL3 VARCHAR(5),
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DEL_FLG CHAR(1) DEFAULT 0
);

-- 注文情報リスト --
CREATE TABLE `PURCHASE_LST` (
  `ORDER_ID` varchar(25) NOT NULL default '',
  `CUSTOMER_ID` varchar(25) NOT NULL default '',
  `TOTAL_PRICE` int(10) unsigned default NULL,
  `SUM_PRICE` int(10) unsigned default NULL,
  `SHIPPING_AMOUNT` int(10) unsigned default NULL,
  `DAIBIKI_AMOUNT` int(10) unsigned default NULL,
  `CONV_AMOUNT` int(10) unsigned default NULL,
  `DELI_LAST_NAME` tinytext,
  `DELI_FIRST_NAME` tinytext,
  `DELI_ZIP_CD1` char(3) default NULL,
  `DELI_ZIP_CD2` varchar(4) default NULL,
  `DELI_STATE` char(2) default NULL,
  `DELI_ADDRESS1` tinytext,
  `DELI_ADDRESS2` tinytext,
  `DELI_TEL1` varchar(5) default NULL,
  `DELI_TEL2` varchar(5) default NULL,
  `DELI_TEL3` varchar(5) default NULL,
  `LAST_NAME` tinytext,
  `FIRST_NAME` tinytext,
  `ZIP_CD1` char(3) default NULL,
  `ZIP_CD2` varchar(4) default NULL,
  `STATE` char(2) default NULL,
  `ADDRESS1` tinytext,
  `ADDRESS2` tinytext,
  `TEL1` varchar(5) default NULL,
  `TEL2` varchar(5) default NULL,
  `TEL3` varchar(5) default NULL,
  `PAYMENT_TYPE` char(1) default NULL,
  `CONV_NO` varchar(16) default NULL,
  `ORDER_DATE` datetime default NULL,
  `PAYMENT_FLG` char(1) default NULL,
  `PAYMENT_DATE` datetime default NULL,
  `SHIPPED_FLG` char(1) default NULL,
  `SHIPPED_DAY` datetime default NULL,
  `REMARKS` text,
  `CONFIG_MEMO` text,
  `CREDIT_CLOSE_FLG` char(1) default '0',
  `UPD_DATE` datetime default NULL,
  `DEL_FLG` char(1) default '0',
  PRIMARY KEY  (`ORDER_ID`)
);

-- 注文商品一覧 --
CREATE TABLE `PURCHASE_ITEM_DATA` (
  `PID` bigint(20) unsigned NOT NULL auto_increment,
  `ORDER_ID` varchar(25) NOT NULL default '',
  `PROPERTY_ID` bigint(20) unsigned NOT NULL default '0',
  `PART_NO` tinytext,
  `PRODUCT_NAME` tinytext,
  `COLOR_NAME` tinytext,
  `SIZE_NAME` tinytext,
  `SELLING_PRICE` int(10) unsigned NOT NULL default '0',
  `QUANTITY` int(10) unsigned default NULL,
  `INS_DATE` datetime default NULL,
  `DEL_FLG` char(1) default '0',
  PRIMARY KEY  (`PID`)
);

-- カテゴリ --
CREATE TABLE CATEGORY_MST(
	CATEGORY_CODE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY_NAME TINYTEXT,
	CATEGORY_DETAILS TINYTEXT,
	VIEW_ORDER INT UNSIGNED,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DEL_FLG CHAR(1) DEFAULT 0
);
INSERT INTO CATEGORY_MST (CATEGORY_CODE,CATEGORY_NAME,CATEGORY_DETAILS,VIEW_ORDER,INS_DATE,UPD_DATE,DEL_FLG) VALUES(1,'','',1,'','','0');

-- 商品情報 --
CREATE TABLE PRODUCT_LST(
	PRODUCT_ID VARCHAR(25) NOT NULL PRIMARY KEY,
	CATEGORY_CODE INT UNSIGNED NOT NULL,
	PART_NO TINYTEXT,
	PRODUCT_NAME TEXT,
	CAPACITY TEXT,
	PRODUCT_DETAILS TEXT,
	ITEM_DETAILS TEXT,
	TITLE_TAG TEXT,
	STOCK_QUANTITY INT UNSIGNED DEFAULT 0,
	SELLING_PRICE INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	CART_CLOSE_FLG CHAR(1) DEFAULT 0,
	NEW_ITEM_FLG CHAR(1) DEFAULT 0,
	RECOMMEND_FLG CHAR(1) DEFAULT 0,
	RECOMMEND_VO INT UNSIGNED,
	VIEW_ORDER INT UNSIGNED,
	SALE_START_DATE DATETIME,
	SALE_END_DATE DATETIME,
	INS_DATE DATETIME,
	UPD_DATE DATETIME,
	DEL_FLG CHAR(1) DEFAULT 0
);

CREATE TABLE `PRODUCT_PROPERTY_DATA` (
  `DSC_ID` bigint(20) unsigned NOT NULL auto_increment,
  `PRODUCT_ID` varchar(25) NOT NULL default '',
  `SIZE_CODE` varchar(25) NOT NULL default '',
  `STOCK_QUANTITY` int(10) unsigned NOT NULL default '0',
  `INS_DATE` datetime default NULL,
  `UPD_DATE` datetime default NULL,
  `DEL_FLG` char(1) default '0',
  `NOT_CS_FLG` char(1) default '0',
  PRIMARY KEY  (`DSC_ID`)
) ;

CREATE TABLE `COLOR_MST` (
  `COLOR_CODE` int(10) unsigned NOT NULL auto_increment,
  `COPY_ID` varchar(25) default NULL,
  `COLOR_NAME` tinytext,
  `COLOR_DETAILS` tinytext,
  `VIEW_ORDER` int(10) unsigned default NULL,
  `INS_DATE` datetime default NULL,
  `UPD_DATE` datetime default NULL,
  `DEL_FLG` char(1) default '0',
  `DISPLAY_FLG` char(1) NOT NULL default '',
  PRIMARY KEY  (`COLOR_CODE`)
);

CREATE TABLE `SIZE_MST` (
  `COLOR_CODE` int(10) unsigned default NULL,
  `SIZE_CODE` int(10) unsigned NOT NULL auto_increment,
  `SIZE_NAME` tinytext,
  `SIZE_DETAILS` tinytext,
  `VIEW_ORDER` int(10) unsigned default NULL,
  `INS_DATE` datetime default NULL,
  `UPD_DATE` datetime default NULL,
  `DEL_FLG` char(1) default '0',
  `DISPLAY_FLG` char(1) NOT NULL default '',
  PRIMARY KEY  (`SIZE_CODE`)
);

CREATE TABLE IF NOT EXISTS `SHOP_TAX_CONFIG_MST` (
  `TAX` int(11) unsigned NOT NULL COMMENT '税率',
  `TAX_FLOAT` char(1) default '0' COMMENT '税金の小数点処理判定'
);

INSERT INTO `SHOP_TAX_CONFIG_MST` (`TAX`, `TAX_FLOAT`) VALUES
(8, '0');
