CREATE TABLE S6_3PRODUCT2_LST(
	RES_ID VARCHAR(25) NOT NULL,
	TITLE TEXT,
	CONTENT TEXT,
	DETAIL_CONTENT TEXT,
	TITLE_TAG TEXT,
	YOUTUBE TEXT,
	IMG_FLG CHAR(1) DEFAULT 1,
	DISP_DATE DATETIME,
	VIEW_ORDER INT UNSIGNED,
	DISPLAY_FLG CHAR(1) DEFAULT 1,
	UPD_DATE TIMESTAMP,
	DEL_FLG CHAR(1) DEFAULT 0,
	PRIMARY KEY(RES_ID)
);
