
--
-- テーブルの構造 `CP1_CATEGORY_MST`
--

CREATE TABLE `CP1_CATEGORY_MST` (
  `CATEGORY_CODE` int(10) unsigned NOT NULL auto_increment,
  `CATEGORY_NAME` text,
  `CATEGORY_DETAILS` text,
  `VIEW_ORDER` int(10) unsigned default NULL,
  `INS_DATE` datetime default NULL,
  `UPD_DATE` datetime default NULL,
  `DISPLAY_FLG` char(1) default '1',
  `DEL_FLG` char(1) default '0',
  PRIMARY KEY  (`CATEGORY_CODE`)
);

-- --------------------------------------------------------

--
-- テーブルの構造 `CP1_PAGE_LST`
--

CREATE TABLE `CP1_PAGE_LST` (
  `RES_ID` varchar(25) NOT NULL default '',
  `CATEGORY_CODE` int(10) default NULL,
  `CONTENT` text,
  `TITLE` text,
  `USE_BLOCK` text,
  `AFLASH_FLG` char(1) default '0',
  `AREADER_FLG` char(1) default '0',
  `DISP_DATE` datetime default NULL,
  `VIEW_ORDER` int(10) unsigned default NULL,
  `DISPLAY_FLG` char(1) default '1',
  `SEO_KEYWORDS` text,
  `SEO_DESCRIPTION` text,
  `SEO_H1` text,
  `LST_DISPLAY_FLG` char(1) default '1',
  `INS_DATE` timestamp NULL default NULL,
  `UPD_DATE` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `DEL_FLG` char(1) default '0',
  PRIMARY KEY  (`RES_ID`)
) ;

-- --------------------------------------------------------

--
-- テーブルの構造 `CP1_VALUES_LST`
--

CREATE TABLE `CP1_VALUES_LST` (
  `RES_ID` varchar(25) NOT NULL default '',
  `PAGE_ID` varchar(25) NOT NULL default '',
  `BLOCK_ID` int(3) unsigned default NULL,
  `TEXT1` text,
  `TEXT2` text,
  `TEXT3` text,
  `TEXT4` text,
  `TEXT5` text,
  `TEXT6` text,
  `TEXT7` text,
  `TEXT8` text,
  `TEXT9` text,
  `TEXT10` text,
  `TEXT11` text,
  `TEXT12` text,
  `TEXT13` text,
  `TEXT14` text,
  `TEXT15` text,
  `TEXT16` text,
  `TEXT17` text,
  `TEXT18` text,
  `TEXT19` text,
  `TEXT20` text,
  `TEXT21` text,
  `TEXT22` text,
  `TEXT23` text,
  `TEXT24` text,
  `TEXT25` text,
  `TEXT26` text,
  `TEXT27` text,
  `TEXT28` text,
  `TEXT29` text,
  `TEXT30` text,
  `TEXT31` text,
  `TEXT32` text,
  `TEXT33` text,
  `TEXT34` text,
  `TEXT35` text,
  `TEXT36` text,
  `TEXT37` text,
  `TEXT38` text,
  `TEXT39` text,
  `TEXT40` text,
  `TEXT41` text,
  `TEXT42` text,
  `TEXT43` text,
  `TEXT44` text,
  `TEXT45` text,
  `TEXT46` text,
  `TEXT47` text,
  `TEXT48` text,
  `TEXT49` text,
  `TEXT50` text,
  `TEXT51` text,
  `TEXT52` text,
  `TEXT53` text,
  `TEXT54` text,
  `TEXT55` text,
  `TEXT56` text,
  `TEXT57` text,
  `TEXT58` text,
  `TEXT59` text,
  `TEXT60` text,
  `TEXT61` text,
  `TEXT62` text,
  `TEXT63` text,
  `TEXT64` text,
  `TEXT65` text,
  `TEXT66` text,
  `TEXT67` text,
  `TEXT68` text,
  `TEXT69` text,
  `TEXT70` text,
  `TEXT71` text,
  `TEXT72` text,
  `TEXT73` text,
  `TEXT74` text,
  `TEXT75` text,
  `TEXT76` text,
  `TEXT77` text,
  `TEXT78` text,
  `TEXT79` text,
  `TEXT80` text,
  `TEXT81` text,
  `TEXT82` text,
  `TEXT83` text,
  `TEXT84` text,
  `TEXT85` text,
  `TEXT86` text,
  `TEXT87` text,
  `TEXT88` text,
  `TEXT89` text,
  `TEXT90` text,
  `TEXT91` text,
  `TEXT92` text,
  `TEXT93` text,
  `TEXT94` text,
  `TEXT95` text,
  `TEXT96` text,
  `TEXT97` text,
  `TEXT98` text,
  `TEXT99` text,
  `TEXT100` text,
  `FILE1` varchar(128) default NULL,
  `FILE2` varchar(128) default NULL,
  `FILE3` varchar(128) default NULL,
  `FILE4` varchar(128) default NULL,
  `FILE5` varchar(128) default NULL,
  `FILE6` varchar(128) default NULL,
  `FILE7` varchar(128) default NULL,
  `FILE8` varchar(128) default NULL,
  `FILE9` varchar(128) default NULL,
  `FILE10` varchar(128) default NULL,
  `FPARAM1` text,
  `FPARAM2` text,
  `FPARAM3` text,
  `FPARAM4` text,
  `FPARAM5` text,
  `FPARAM6` text,
  `FPARAM7` text,
  `FPARAM8` text,
  `FPARAM9` text,
  `FPARAM10` text,
  `VIEW_ORDER` int(10) unsigned default NULL,
  `UPD_DATE` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `DEL_FLG` char(1) default '0',
  PRIMARY KEY  (`RES_ID`)
) ;
